title: Colette Baker
logo: /assets/img/headshot.jpg
description: 
  Sustainability Manager for Harvard Medical School and Harvard School of Dental Medicine
  
    <br>
    Data Scientist
    
    <br>
       <a href="https://github.com/user-attachments/files/17281156/Baker.Resume.pdf">View My Resume</a>
    <br>
  <a href="www.linkedin.com/in/colette-baker-91a96812a">View My LinkedIn Profile</a> 



#show_downloads: false
theme: jekyll-theme-minimal
